name: First Teting Job
on: push
jobs:
    Testing-Echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Testing Echo Job"
    second-job:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "I will fail"
                exit 1
            - run: echo "Good Bye"
            