name: First Teting Job
on:
   workflow_dispatch:
jobs:
    Testing-Echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Testing Echo Job"
    second-job:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "I will success"
                exit 0
            - run: echo "Good Bye"
            